---
title: <span style="color:#686868"> **Referencias**</span>
author: "Métodos y Simulación Estadística"
output:
  html_document:
    toc: no
    toc_depth: 2
    toc_float: yes
    code_folding: hide
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = NA)

```

<div class="caja-referencia">
<h3>Conceptos básicos:</h3>
<p>
Kolmogorov, A. N. (1933). <em>Foundations of the theory of probability</em>. Chelsea Publishing Company.
</p>
<p>
Fisher, R. A. (1959). <em>Statistical methods and scientific inference</em>. Oliver and Boyd.
</p>
<p>
Walpole, R. E. (2012). <em>Probability and statistics for engineers and scientists</em> (9th ed.). Pearson Education.</p>
<p>Anderson, D. R. (2013). <em>Modern business statistics with Microsoft Excel</em> (5th ed.). Cengage Learning.
</p>
<p>
Hill, A. B. (1965). The environment and disease: Association or causation? <em>Proceedings of the Royal Society of Medicine, 58</em>(5), 295–300. <a href="https://doi.org/10.1177/003591576505800503" target="_blank">https://doi.org/10.1177/003591576505800503</a>
</p>
<p>
Scheaffer, R. L., Mendenhall, W., & Ott, L. (2006). <em>Elementos de muestreo</em>. Paraninfo.
</p>
</div>

<br/>
<div class="caja-referencia">
<h3>Ordenar:</h3>
<p>
Rubin, D. B. (1976). Inference and missing data. <em>Biometrika</em>, 63</em>(3), 581–592. DOI: <a href="https://doi.org/10.1093/biomet/63.3.581" target="_blank">https://doi.org/10.1093/biomet/63.3.581</a>
 </p>
</div>


<br/>
<div class="caja-referencia">
<h3>Software R:</h3>
<p>
Xie, Y. (n.d.). <em>bookdown: Authoring books and technical documents with R Markdown</em>. <a href="https://bookdown.org/yihui/bookdown/" target="_blank">https://bookdown.org/yihui/bookdown/</a>
</p>
<p>
Çetinkaya-Rundel, M., & Hardin, J. (n.d.). <em>Statistical inference via data science</em>. <a href="https://moderndive.com/" target="_blank">https://moderndive.com/</a>
</p>
<p>
Wickham, H., & Grolemund, G. (n.d.). <em>R for data science</em>. <a href="https://r4ds.had.co.nz/" target="_blank">https://r4ds.had.co.nz/</a>
</p>
</div>
